title: 'Open Election Data Initiative'
email: openelectiondata@ndi.org
description: ''
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://openelectiondata.net' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:

google_analytics:

date_format: '%B %-d, %Y'

cloudinary_url: https://res.cloudinary.com/csisideaslab/image/upload/

# Content types will be defined here
collections:
  posts:
    title: Blog
    output: false
  guide:
    title: Election Data Guide
    output: true
  inventory:
    title: Latin America Data Inventory
    output: true
  academy:
    title: Academy
    output: true

# Default front matter values for a collection will be defined here
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: post
      permalink: '/blog/:slug/'
      view_all_url: '/blog/'
      breadcrumbs: true
  - scope:
      path: ''
      type: 'guide'
    values:
      layout: page-sidebar
      permalink: '/guide/:slug/'
  - scope:
      path: ''
      type: 'inventory'
    values:
      layout: page
      permalink: '/inventory/:slug/'
  - scope:
      path: ''
      type: 'academy'
    values:
      layout: page-sidebar
      permalink: '/academy/:slug/'

# Translation Settings
languages: ['en', 'es', 'ru']
default_lang: 'xx'
exclude_from_localization: ['assets']
parallel_localization: true

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-polyglot

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - gulp.config.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - INCLUDES.md
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - prettier.config.js
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
