# Content negotiation for home page
[[redirects]]
  from = "/"
  to = "/es/"
  status = 200
  conditions = {Language = ["es"]}

# Content negotiation for home page
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200

# Redirect for end-user’s browser preference override
[[redirects]]
  from = "/*"
  to = "/es/:splat"
  status = 302
  conditions = {Language = ["es"]}

# Default
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302